"""clean baseline

Revision ID: 56aa41542075
Revises: 
Create Date: 2026-06-28 16:35:59.365618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '56aa41542075'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_profiles',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_profiles_code'), 'template_profiles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ISSUES', 'FAILED', 'FAILED_SOURCE_UNAVAILABLE', name='job_status_enum'), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('source_file_path', sa.String(length=1024), nullable=False),
    sa.Column('result_file_path', sa.String(length=1024), nullable=True),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('ambiguous_count', sa.Integer(), nullable=False),
    sa.Column('source_uncertain_count', sa.Integer(), nullable=False),
    sa.Column('placeholder_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'UPLOAD_CREATED', 'JOB_RUN_REQUESTED', 'JOB_PROCESSING_STARTED', 'JOB_PROCESSING_COMPLETED', 'JOB_PROCESSING_FAILED', 'FILE_DOWNLOADED', name='audit_action_enum'), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('file_objects',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('SOURCE', 'RESULT', 'REPORT', name='file_object_type_enum'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_objects_job_id'), 'file_objects', ['job_id'], unique=False)
    op.create_table('job_items',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('excel_row', sa.Integer(), nullable=False),
    sa.Column('device_kind', sa.String(length=10), nullable=False),
    sa.Column('block_code', sa.String(length=50), nullable=False),
    sa.Column('type_raw', sa.String(length=255), nullable=True),
    sa.Column('type_norm', sa.String(length=255), nullable=True),
    sa.Column('serial_raw', sa.String(length=255), nullable=True),
    sa.Column('serial_norm', sa.String(length=255), nullable=True),
    sa.Column('accuracy_class_raw', sa.String(length=50), nullable=True),
    sa.Column('verification_date_file_raw', sa.String(length=50), nullable=True),
    sa.Column('verification_date_file_norm', sa.Date(), nullable=True),
    sa.Column('next_date_file_raw', sa.String(length=50), nullable=True),
    sa.Column('next_date_file_norm', sa.Date(), nullable=True),
    sa.Column('link_file_raw', sa.String(length=1024), nullable=True),
    sa.Column('link_file_vri', sa.String(length=255), nullable=True),
    sa.Column('cell_type', sa.String(length=20), nullable=True),
    sa.Column('cell_serial', sa.String(length=20), nullable=True),
    sa.Column('cell_verification_date', sa.String(length=20), nullable=True),
    sa.Column('cell_next_date', sa.String(length=20), nullable=True),
    sa.Column('cell_link', sa.String(length=20), nullable=True),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'MISMATCH', 'AMBIGUOUS', 'SOURCE_UNCERTAIN', 'PLACEHOLDER', 'MISSING_DATA', 'ERROR', name='job_item_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_items_job_id'), 'job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_items_status'), 'job_items', ['status'], unique=False)
    op.create_table('arshin_audit',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_item_id', sa.UUID(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('endpoint_mode', sa.String(length=10), nullable=False),
    sa.Column('request_url', sa.String(length=1024), nullable=False),
    sa.Column('request_params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('response_body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transport_error', sa.Text(), nullable=True),
    sa.Column('result_class', sa.Enum('SUCCESS_WITH_MATCH', 'SUCCESS_EMPTY', 'TEMPORARY_SOURCE_FAILURE', 'AMBIGUOUS_MULTIPLE_MATCHES', name='check_result_class_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arshin_audit_job_id'), 'arshin_audit', ['job_id'], unique=False)
    op.create_index(op.f('ix_arshin_audit_job_item_id'), 'arshin_audit', ['job_item_id'], unique=False)
    op.create_index(op.f('ix_arshin_audit_result_class'), 'arshin_audit', ['result_class'], unique=False)
    op.create_table('job_issues',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_item_id', sa.UUID(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('cell', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.Enum('RED', 'YELLOW', 'ORANGE', 'INFO', name='job_issue_severity_enum'), nullable=False),
    sa.Column('code', sa.Enum('MATCH', 'TYPE_MISMATCH', 'SERIAL_MISMATCH', 'VERIFICATION_DATE_MISMATCH', 'NEXT_VERIFICATION_DATE_MISMATCH', 'LINK_MISMATCH', 'LINK_FILLED', 'PLACEHOLDER_VALUE_DETECTED', 'MISSING_REQUIRED_FIELD', 'ARSHIN_NOT_FOUND', 'SOURCE_UNCERTAIN', 'MULTIPLE_MATCHES', name='issue_code_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_issues_code'), 'job_issues', ['code'], unique=False)
    op.create_index(op.f('ix_job_issues_job_id'), 'job_issues', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_issues_job_item_id'), 'job_issues', ['job_item_id'], unique=False)
    op.create_index(op.f('ix_job_issues_severity'), 'job_issues', ['severity'], unique=False)
    op.create_table('job_item_checks',
    sa.Column('job_item_id', sa.UUID(), nullable=False),
    sa.Column('arshin_found', sa.Boolean(), nullable=False),
    sa.Column('selected_vri_id', sa.String(length=255), nullable=True),
    sa.Column('selected_url', sa.String(length=1024), nullable=True),
    sa.Column('arshin_type', sa.String(length=255), nullable=True),
    sa.Column('arshin_serial', sa.String(length=255), nullable=True),
    sa.Column('arshin_verification_date', sa.Date(), nullable=True),
    sa.Column('arshin_valid_date', sa.Date(), nullable=True),
    sa.Column('arshin_applicability', sa.Boolean(), nullable=True),
    sa.Column('candidates_count', sa.Integer(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('result_class', sa.Enum('SUCCESS_WITH_MATCH', 'SUCCESS_EMPTY', 'TEMPORARY_SOURCE_FAILURE', 'AMBIGUOUS_MULTIPLE_MATCHES', name='check_result_class_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_item_checks_job_item_id'), 'job_item_checks', ['job_item_id'], unique=False)
    op.create_index(op.f('ix_job_item_checks_result_class'), 'job_item_checks', ['result_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_item_checks_result_class'), table_name='job_item_checks')
    op.drop_index(op.f('ix_job_item_checks_job_item_id'), table_name='job_item_checks')
    op.drop_table('job_item_checks')
    op.drop_index(op.f('ix_job_issues_severity'), table_name='job_issues')
    op.drop_index(op.f('ix_job_issues_job_item_id'), table_name='job_issues')
    op.drop_index(op.f('ix_job_issues_job_id'), table_name='job_issues')
    op.drop_index(op.f('ix_job_issues_code'), table_name='job_issues')
    op.drop_table('job_issues')
    op.drop_index(op.f('ix_arshin_audit_result_class'), table_name='arshin_audit')
    op.drop_index(op.f('ix_arshin_audit_job_item_id'), table_name='arshin_audit')
    op.drop_index(op.f('ix_arshin_audit_job_id'), table_name='arshin_audit')
    op.drop_table('arshin_audit')
    op.drop_index(op.f('ix_job_items_status'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_job_id'), table_name='job_items')
    op.drop_table('job_items')
    op.drop_index(op.f('ix_file_objects_job_id'), table_name='file_objects')
    op.drop_table('file_objects')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_template_profiles_code'), table_name='template_profiles')
    op.drop_table('template_profiles')
    # ### end Alembic commands ###
