"""add job progress and priority fields

Revision ID: 99008d90d7ea
Revises: cab9930a4af1
Create Date: 2026-07-12 15:34:33.621004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '99008d90d7ea'
down_revision: Union[str, None] = 'cab9930a4af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('processed_items', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('current_item_label', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('jobs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_column('jobs', 'queued_at')
    op.drop_column('jobs', 'priority')
    op.drop_column('jobs', 'current_item_label')
    op.drop_column('jobs', 'processed_items')
    # ### end Alembic commands ###
