"""add mitnumber_registry

Revision ID: cab9930a4af1
Revises: 7a1b2c3d4e5f
Create Date: 2026-07-12 14:13:28.296066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'cab9930a4af1'
down_revision: Union[str, None] = '7a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitnumber_registry',
    sa.Column('model_root', sa.String(length=255), nullable=False),
    sa.Column('matched_pattern', sa.String(length=255), nullable=False),
    sa.Column('mitnumbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitnumber_registry_model_root'), 'mitnumber_registry', ['model_root'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitnumber_registry_model_root'), table_name='mitnumber_registry')
    op.drop_table('mitnumber_registry')
    # ### end Alembic commands ###
